# Generated by Django 4.2.17 on 2025-01-14 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='code',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='email',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
